import wollok.lang.Exception

class BusinessException inherits Exception {
	constructor(_message) {message = _message}
}

test "Use throwsExceptionWithMessage" {

	assert.throwsExceptionWithMessage("hola!", { => throw new BusinessException("hola!") })

}