
test "Test exception from native method gets wrapped into a WollokException" {
	assert.throwsException { 2 / 0 }
}
